---
title: "Analysis of U.S. Storm Event Data and the Impact on Public Health and the Economy"
author: "Jeffrey Hunter"
date: "4/23/2019"
output:
  html_document:
    df_print: paged
  pdf_document: default
  html_notebook: default
  pdf_notebook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Table of Contents

[Introduction](#introduction)<br />
[Synonpsis](#synonpsis)<br />
[Set up environment](#set-up-environment)<br />
[Load Data](#load-data)<br />
[Data Processing](#data-processing)<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [Impact on Public Health](#impact-on-public-health)<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [Impact on Economy](#impact-on-economy)<br />
[Results](#results)<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [Event Types Most Harmful to Population Health](#event-types-most-harmful-to-population-health)<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [Event Types with Greatest Economic Consequences](#event-types-with-greatest-economic-consequences)<br />
[Conclusion](#conclusion)

## Introduction

*pending*

## Synonpsis

*pending*

## Set up environment

*pending*

## Load Data

*pending*

## Data Processing

### Impact on Public Health

*pending*

### Impact on Economy

*pending*

## Results

### Event Types Most Harmful to Population Health

*pending*

### Event Types with Greatest Economic Consequences

*pending*

## Conclusion

*pending*





